use_frameworks!

platform :ios, '8.0'

target 'ApexDataCollect-Visual_Example' do
  pod 'ApexDataCollect-Visual', :path => '../'

  target 'ApexDataCollect-Visual_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
